version: "3.9"

services:
  database:
    container_name: postgres_db
    image: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    user: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 2s
      timeout: 2s
      retries: 5

  app:
    container_name: spartan_app
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
