"""auto_20210908_4

Revision ID: 03d3c3e431a4
Revises: ac413ad73d90
Create Date: 2021-09-08 14:10:59.736440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d3c3e431a4'
down_revision = 'ac413ad73d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id')
    )
    op.create_index(op.f('ix_association_id'), 'association', ['id'], unique=False)
    op.drop_constraint('user_team_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_team_id_fkey', 'user', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_association_id'), table_name='association')
    op.drop_table('association')
    # ### end Alembic commands ###
