"""auto_20210908_3

Revision ID: ac413ad73d90
Revises: cf9818467e06
Create Date: 2021-09-08 03:51:01.465902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac413ad73d90'
down_revision = 'cf9818467e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_team_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_team_id_fkey', 'user', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###
