"""auto_20210908_1

Revision ID: eb6c2c7148ad
Revises: 433e608628d6
Create Date: 2021-09-08 02:29:30.109238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6c2c7148ad'
down_revision = '433e608628d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'team', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='unique')
    # ### end Alembic commands ###
